### ISSUE TITLE
Question regarding Sketch API

### ISSUE THREAD

**Issue by florianpeninon** [KivyGogh/Coffee-Slice#1]
Hi,

I was looking at your code to understand how you succeeded to make this plugin works and I'm wondering how did you come accross the `MSSliceLayer.new()` ?
I haven't seen it in any documentation or even in the Class Dump from Sketch.

I'm building plugins as well and I'm wondering if I'm missing a nice tool to find these tricks or if you just tried until you found it :)

Cheers!

**Comment by KivyGogh** [comment]
`MSSliceLayer` is in the list of classes of Sketch:http://developer.sketchapp.com/reference/class/MSSliceLayer/

and I have ever read many Sketch plugins' code,I remember that someone else used `MSLayer.new()`to creating a new layer,so I  just borrowed its thinking and got a successful try :)

Looking forward to your amazing work !

**Comment by florianpeninon** [comment]
Oh I completely missed that new website!
Thanks for pointing towards it.

I hope it will be amazing but I'm a long way from it :)
