### ISSUE TITLE
Small Typo

### ISSUE THREAD

**Issue by jydesign** [KivyGogh/Coffee-Slice#2]
Nice work. I noticed a typo in your title: "A Sketch plugin to make the standard slicing with a user-given viewBox size automaticlly." 

automaticlly should be automatically

regards J.

**Comment by KivyGogh** [comment]
Oh...a diabolical error....I'll rectify it right away~
thank you very much !!!

**Comment by KivyGogh** [comment]
Oh...a diabolical error....I'll rectify it right away~
thank you very much !!!
